process ASSEMBLY_STATS {
    /*
        ASSEMBLY_STATS Process
        Written by Reed Woyda under the Wrighton Lab at Colorado State University.
        November 2023
    */

    errorStrategy 'finish'  // Finish the process even if errors occur

    // Add an ID tag to the process
    tag { sample }

    // Define the input for the ASSEMBLY_STATS process
    input:
        // Input is a tuple consisting of a set of contigs with an associated sample, iteration_flag, and iteration_count
        tuple val(sample), val(iteration_flag), val(iteration_count), path(contigs)
        path(contig_stats_script)
    
    // Define the output for ASSEMBLY_STATS process, including assembly statistics log files
    output:
        // Output is a tuple consisting of a path to assembly statistics log files associated with the sample, iteration_flag, and iteration_count
        path("${sample}*.txt"), emit: assembly_stats_log, optional: true

    // Bash script for ASSEMBLY_STATS process
    script:
    """
    if [[ -s "${contigs}" ]]; then
        # Calculate assembly statistics for the provided contigs
        perl ${contig_stats_script} \\
        -i "${contigs}" \\
        -o "${sample}.contigs_STATS"    
    else
        # Error message if no contigs were generated by the assembler
        echo "Sample ${sample} - Error: No contigs >= ${params.min_contig_len} were generated by ${params.assembler}."
    fi
    """
}
